// src/lib/errors/codes.ts

export const ErrorCodes = {
  // Student
  STUDENT_NAME_REQUIRED: "STUDENT_NAME_REQUIRED",
  STUDENT_NAME_DUPLICATE: "STUDENT_NAME_DUPLICATE",
  STUDENT_NOT_FOUND: "STUDENT_NOT_FOUND",
  STUDENT_PHONE_INVALID_FORMAT: "STUDENT_PHONE_INVALID_FORMAT",

  // Subject
  SUBJECT_NAME_REQUIRED: "SUBJECT_NAME_REQUIRED",
  SUBJECT_NAME_DUPLICATE: "SUBJECT_NAME_DUPLICATE",
  SUBJECT_NOT_FOUND: "SUBJECT_NOT_FOUND",

  // Session
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  SESSION_TIME_INVALID: "SESSION_TIME_INVALID",
  SESSION_DURATION_EXCEEDED: "SESSION_DURATION_EXCEEDED",

  // Invite
  INVITE_TOKEN_EXPIRED: "INVITE_TOKEN_EXPIRED",
  INVITE_TOKEN_USED: "INVITE_TOKEN_USED",
  INVITE_ROLE_INVALID: "INVITE_ROLE_INVALID",
  INVITE_MEMBER_INSERT_FAILED: "INVITE_MEMBER_INSERT_FAILED",

  // General (HTTP 의미론적 범용 에러 — {ENTITY}_{FIELD}_{RULE} 세그먼트 예외 허용)
  VALIDATION_FAILED: "VALIDATION_FAILED",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
