// src/lib/errors/codes.ts

export const ErrorCodes = {
  // Student
  STUDENT_NAME_REQUIRED: "STUDENT_NAME_REQUIRED",
  STUDENT_NAME_DUPLICATE: "STUDENT_NAME_DUPLICATE",
  STUDENT_NAME_TOO_LONG: "STUDENT_NAME_TOO_LONG",
  STUDENT_NOT_FOUND: "STUDENT_NOT_FOUND",
  STUDENT_GRADE_INVALID: "STUDENT_GRADE_INVALID",
  STUDENT_GENDER_INVALID: "STUDENT_GENDER_INVALID",
  STUDENT_SCHOOL_TOO_LONG: "STUDENT_SCHOOL_TOO_LONG",
  STUDENT_BIRTHDATE_OUT_OF_RANGE: "STUDENT_BIRTHDATE_OUT_OF_RANGE",
  PHONE_INVALID_FORMAT: "PHONE_INVALID_FORMAT",

  // Teacher
  TEACHER_NAME_REQUIRED: "TEACHER_NAME_REQUIRED",
  TEACHER_NAME_DUPLICATE: "TEACHER_NAME_DUPLICATE",
  TEACHER_NAME_TOO_LONG: "TEACHER_NAME_TOO_LONG",
  TEACHER_EMAIL_INVALID: "TEACHER_EMAIL_INVALID",

  // Subject
  SUBJECT_NAME_REQUIRED: "SUBJECT_NAME_REQUIRED",
  SUBJECT_NAME_DUPLICATE: "SUBJECT_NAME_DUPLICATE",
  SUBJECT_NAME_TOO_LONG: "SUBJECT_NAME_TOO_LONG",
  SUBJECT_NOT_FOUND: "SUBJECT_NOT_FOUND",

  // Academy
  ACADEMY_NAME_REQUIRED: "ACADEMY_NAME_REQUIRED",
  ACADEMY_NAME_TOO_LONG: "ACADEMY_NAME_TOO_LONG",

  // Session
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  SESSION_TIME_INVALID: "SESSION_TIME_INVALID",
  SESSION_DURATION_EXCEEDED: "SESSION_DURATION_EXCEEDED",

  // Invite
  INVITE_TOKEN_EXPIRED: "INVITE_TOKEN_EXPIRED",
  INVITE_TOKEN_USED: "INVITE_TOKEN_USED",
  INVITE_ROLE_INVALID: "INVITE_ROLE_INVALID",
  INVITE_MEMBER_INSERT_FAILED: "INVITE_MEMBER_INSERT_FAILED",

  // Snapshot
  SNAPSHOT_TYPE_INVALID: "SNAPSHOT_TYPE_INVALID",
  SNAPSHOT_PAYLOAD_REQUIRED: "SNAPSHOT_PAYLOAD_REQUIRED",
  SNAPSHOT_INSERT_FAILED: "SNAPSHOT_INSERT_FAILED",
  SNAPSHOT_LIST_FAILED: "SNAPSHOT_LIST_FAILED",
  SNAPSHOT_PERMISSION_DENIED: "SNAPSHOT_PERMISSION_DENIED",

  // General (HTTP 의미론적 범용 에러 — {ENTITY}_{FIELD}_{RULE} 세그먼트 예외 허용)
  VALIDATION_FAILED: "VALIDATION_FAILED",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
